<a href="https://colab.research.google.com/github/XOSDX/Implementing-Artificial-Neural-Network-training-process-in-Python/blob/main/DEEP_LEARNING_PART_3_Activation_Functions_in_Pytorch.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [8]:
!pip install torch

In [21]:
import torch
import torch.nn as nn
import matplotlib.pyplot as plt
%matplotlib inline

In [12]:
print('Activation functions using pytorch')

Activation functions using pytorch


In [25]:
r1=nn.ReLU()
input1=torch.Tensor([1,-3,4,2])
output1=r1(input1)
output1

tensor([1., 0., 4., 2.])

In [27]:
r2=nn.LeakyReLU(0.2)
input2=torch.Tensor([0,-6,5,4])
output2=r2(input2)
output2

tensor([ 0.0000, -1.2000,  5.0000,  4.0000])

In [29]:
r3=nn.Sigmoid()
input3=torch.Tensor([-3,5,-6,7])
output3=r3(input3)
output3

tensor([0.0474, 0.9933, 0.0025, 0.9991])

In [30]:
r4=nn.Tanh()
input4=torch.Tensor([4,2,7,4])
output4=r4(input4)
output4

tensor([0.9993, 0.9640, 1.0000, 0.9993])

In [40]:
r5=nn.Softmax(dim=0)
input5=torch.Tensor([3,6,7,2])
output5=r5(input5)
output5

tensor([0.0131, 0.2641, 0.7179, 0.0048])